import {
  AppleIcon,
  ArrowLeftRightIcon,
  BabyIcon,
  BathIcon,
  BedIcon,
  BeerIcon,
  BriefcaseIcon,
  Building2Icon,
  BuildingIcon,
  BusIcon,
  CarIcon,
  CarTaxiFrontIcon,
  CloudIcon,
  CoinsIcon,
  CreditCardIcon,
  DropletIcon,
  DumbbellIcon,
  EllipsisIcon,
  FilmIcon,
  FuelIcon,
  GavelIcon,
  GiftIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HeartPulseIcon,
  HomeIcon,
  LightbulbIcon,
  ListOrderedIcon,
  MilestoneIcon,
  PawPrintIcon,
  PiggyBankIcon,
  PillIcon,
  PizzaIcon,
  PlaneIcon,
  ReceiptIcon,
  RepeatIcon,
  ShapesIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  SprayCanIcon,
  SquareParkingIcon,
  TagIcon,
  TagsIcon,
  TicketIcon,
  TrendingUpIcon,
  TvIcon,
  UsersRoundIcon,
  UtensilsCrossedIcon,
  WalletIcon,
  WifiIcon,
  WrenchIcon,
  ZapIcon,
  type LucideIcon,
} from "lucide-react";

// Predefined palette for category and class icons — matches the icons already used by
// the default-seeded categories (see supabase/migrations/0015_categories_icon.sql).
// Keys are what's stored in categories.icon; "tag" is also the fallback for
// an unrecognized/missing key (see CategoryIcon).
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCartIcon,
  "utensils-crossed": UtensilsCrossedIcon,
  car: CarIcon,
  home: HomeIcon,
  "heart-pulse": HeartPulseIcon,
  film: FilmIcon,
  briefcase: BriefcaseIcon,
  "shopping-bag": ShoppingBagIcon,
  "graduation-cap": GraduationCapIcon,
  plane: PlaneIcon,
  zap: ZapIcon,
  repeat: RepeatIcon,
  gift: GiftIcon,
  "piggy-bank": PiggyBankIcon,
  "trending-up": TrendingUpIcon,
  "arrow-left-right": ArrowLeftRightIcon,
  "paw-print": PawPrintIcon,
  smartphone: SmartphoneIcon,
  wrench: WrenchIcon,
  family: UsersRoundIcon,
  cloud: CloudIcon,
  smile: SmileIcon,
  // Added for classes (see DEFAULT_CLASS_ICON) — also pickable for categories.
  apple: AppleIcon,
  baby: BabyIcon,
  bath: BathIcon,
  bed: BedIcon,
  beer: BeerIcon,
  building: BuildingIcon,
  "building-2": Building2Icon,
  bus: BusIcon,
  "car-taxi-front": CarTaxiFrontIcon,
  coins: CoinsIcon,
  "credit-card": CreditCardIcon,
  droplet: DropletIcon,
  dumbbell: DumbbellIcon,
  ellipsis: EllipsisIcon,
  fuel: FuelIcon,
  gavel: GavelIcon,
  "hand-coins": HandCoinsIcon,
  lightbulb: LightbulbIcon,
  "list-ordered": ListOrderedIcon,
  milestone: MilestoneIcon,
  pill: PillIcon,
  pizza: PizzaIcon,
  receipt: ReceiptIcon,
  shapes: ShapesIcon,
  "shield-check": ShieldCheckIcon,
  sparkles: SparklesIcon,
  "spray-can": SprayCanIcon,
  "square-parking": SquareParkingIcon,
  ticket: TicketIcon,
  tv: TvIcon,
  wallet: WalletIcon,
  wifi: WifiIcon,
  tags: TagsIcon,
  tag: TagIcon,
};

export const CATEGORY_ICONS = Object.keys(CATEGORY_ICON_MAP);

export const DEFAULT_CATEGORY_ICON = "tag";

// Classes share the same icon palette; a new class starts on "tags" (the
// Classes entity icon in sidebar-nav.tsx), matching the DB column default.
export const DEFAULT_CLASS_ICON = "tags";
